---
  - vlan   : 1
    prefix : 1.1.1.1/30
    route  : 11.1.1.1/30
  - vlan   : 2
    prefix : 1.1.2.1/30
    route  : 11.1.2.1/30
  - vlan   : 3
    prefix : 1.1.3.1/30
    route  : 11.1.3.1/30
  - vlan   : 4
    prefix : 1.1.4.1/30
    route  : 11.1.4.1/30
  - vlan   : 5
    prefix : 1.1.5.1/30
    route  : 11.1.5.1/30
